
[en]
  languageName = "English"
  weight = 1
  description = "R-Ladies is a world-wide organization to promote gender diversity in the R community"

[es]
  languageName = "Español"
  weight = 1
  description = "R-Ladies es una organización mundial para promover la diversidad de género en la comunidad R"

[pt]
  languageName = "Português"
  weight = 1
  description = "R-Ladies é uma organização mundial que promove a diversidade de gênero na comunidade R"


[fr]
  languageName = "Français"
  weight = 1
  description = "R-Ladies is a world-wide organization to promote gender diversity in the R community"

