[[main]]
    name = "Página inicial"
    identifier = "home"
    url = "/"
    weight = 1
    
[[main]]
    name = "Sobre nós"
    url = "#"
    identifier = "about-us"
    weight = 2
[[main]]
    name = "Missão"
    url = "/about-us/mission/"
    weight = 1
    parent = "about-us"
[[main]]
    name = "Participe"
    url = "/about-us/involved/"
    weight = 2
    parent = "about-us"
[[main]]
    name = "Conheça o Time Global"
    url = "/about-us/global-team/"
    weight = 3
    parent = "about-us"
[[main]]
    name = "História"
    url = "/about-us/history/"
    weight = 4
    parent = "about-us"
    
[[main]]
    name = "Diretório"
    url = "/directory/"
    weight = 3
    
[[main]]
    name = "Atividades"
    identifier = "activities"
    url = "#"
    weight = 4
[[main]]
    name = "Eventos"
    url = "/activities/events/"
    weight = 1
    parent = "activities"
[[main]]
    name = "Programa de Mentoria"
    url = "/activities/mentoring/"
    weight = 3
    parent = "activities"
[[main]]
    name = "Coordenado pelo Time Global"
    url = "/activities/gt-coordinated/"
    weight = 4
    parent = "activities"
[[main]]
    name = "Dashboard Global"
    url = "https://benubah.github.io/r-community-explorer/rladies.html"
    weight = 5
    parent = "activities"
[[main]]
    name = "Blogs da R-Ladies"
    url = "activities/rladies-blogs"
    weight = 6
    parent = "activities"
    
[[main]]
    name = "Blog"
    url = "/post"
    weight = 5
    
